/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms.view;

import java.rmi.RemoteException;
import java.util.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sms.Model.Courses;
import sms.controller.*;
import sms.Services.IcourseServices;
/**
 *
 * @author hirwa
 */
public class CourseRegistration extends javax.swing.JInternalFrame {
    
    CourseDao crd = new CourseDao();
    StudentRegistration studentregistration = new StudentRegistration();
    IcourseServices courseInterface = new CourseDao();
    
    /**
     * Creates new form CourseView
     */
    public CourseRegistration() {
        initComponents();
        updateTableCourseRegistration();
    }

    public void updateTableCourseRegistration(){
        
        DefaultTableModel model = (DefaultTableModel) courseRegistrationTable.getModel();
        model.setRowCount(0);
        
        List<Courses> lcrs = crd.crList();
        
        for (Courses cr : lcrs) {
            model.insertRow(model.getRowCount(), new Object[]{
                cr.getCourseId(),
                cr.getCourseName(),
                cr.getCredits(),
                cr.getSemester()
            });
        }
    }

    public void resetFields() {
    
        CourseIdField.setText("");
        courseNameField.setText("");
        creditsField.setText("");
        semesterField.setSelectedIndex(0);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseRegistrationTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CourseIdField = new javax.swing.JTextField();
        courseNameField = new javax.swing.JTextField();
        creditsField = new javax.swing.JTextField();
        semesterField = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        courseRegistrationSaveButton = new javax.swing.JButton();
        courseRegistrationUpdateButton = new javax.swing.JButton();
        courseRegistrationDeleteButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Courses");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Course Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        courseRegistrationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Credits", "Semester"
            }
        ));
        courseRegistrationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseRegistrationTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(courseRegistrationTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Course Id");

        jLabel2.setText("Course Name");

        jLabel3.setText("Credits");

        jLabel4.setText("Semester");

        semesterField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CourseIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditsField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(CourseIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(courseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(creditsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(semesterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        courseRegistrationSaveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        courseRegistrationSaveButton.setText("Save");
        courseRegistrationSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseRegistrationSaveButtonActionPerformed(evt);
            }
        });

        courseRegistrationUpdateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        courseRegistrationUpdateButton.setText("Update");
        courseRegistrationUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseRegistrationUpdateButtonActionPerformed(evt);
            }
        });

        courseRegistrationDeleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        courseRegistrationDeleteButton.setText("Delete");
        courseRegistrationDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseRegistrationDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(courseRegistrationUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseRegistrationSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseRegistrationDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(courseRegistrationSaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseRegistrationUpdateButton)
                .addGap(12, 12, 12)
                .addComponent(courseRegistrationDeleteButton)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseRegistrationSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseRegistrationSaveButtonActionPerformed
        try {
            // TODO add your handling code here:
            Courses cr = new Courses();
            
            cr.setCourseId(CourseIdField.getText());
            cr.setCourseName(courseNameField.getText());
            cr.setCredits(creditsField.getText());
            cr.setSemester(semesterField.getSelectedItem().toString());
            
            courseInterface.save(cr);
            
            updateTableCourseRegistration();
            resetFields();
            studentregistration.updateCourseCombobox();
            
            JOptionPane.showMessageDialog(this, "Course Successfully saved!!");
        } catch (RemoteException ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_courseRegistrationSaveButtonActionPerformed

    private void courseRegistrationUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseRegistrationUpdateButtonActionPerformed
        try {
            // TODO add your handling code here:
            Courses cr = new Courses();
            
            cr.setCourseId(CourseIdField.getText());
            cr.setCourseName(courseNameField.getText());
            cr.setCredits(creditsField.getText());
            cr.setSemester(semesterField.getSelectedItem().toString());
            
            courseInterface.update(cr);
            
            updateTableCourseRegistration();
            resetFields();
            studentregistration.updateCourseCombobox();
            
            JOptionPane.showMessageDialog(this, "Updated successfully!!");
        } catch (RemoteException ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_courseRegistrationUpdateButtonActionPerformed

    private void courseRegistrationDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseRegistrationDeleteButtonActionPerformed
        try {
            // TODO add your handling code here:
            Courses cr = new Courses();
            
            cr.setCourseId(CourseIdField.getText());
            cr.setCourseName(courseNameField.getText());
            cr.setCredits(creditsField.getText());
            cr.setSemester(semesterField.getSelectedItem().toString());
            
            IcourseServices courseInterface = new CourseDao();
            courseInterface.delete(cr);
            
            updateTableCourseRegistration();
            studentregistration.updateCourseCombobox();
            resetFields();
            
            JOptionPane.showMessageDialog(this, "Successfully Deleted!!");
        } catch (RemoteException ex) {
            Logger.getLogger(CourseRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_courseRegistrationDeleteButtonActionPerformed

    private void courseRegistrationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseRegistrationTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) courseRegistrationTable.getModel();
        int row = courseRegistrationTable.getSelectedRow();
        
        CourseIdField.setText(model.getValueAt(row, 0).toString());
        courseNameField.setText(model.getValueAt(row, 1).toString());
        creditsField.setText(model.getValueAt(row, 2).toString());
        semesterField.setSelectedItem(model.getValueAt(row, 3).toString());
        
    }//GEN-LAST:event_courseRegistrationTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseIdField;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField courseNameField;
    private javax.swing.JButton courseRegistrationDeleteButton;
    private javax.swing.JButton courseRegistrationSaveButton;
    private javax.swing.JTable courseRegistrationTable;
    private javax.swing.JButton courseRegistrationUpdateButton;
    private javax.swing.JTextField creditsField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> semesterField;
    // End of variables declaration//GEN-END:variables
   
    
}
